loki:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClassName: loki-storage
    existingClaim: loki-pvc
  image:
    repository: grafana/loki
    tag: 2.9.3
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 7d

promtail:
  enabled: true
  config:
    server:
      http_listen_port: 3101
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
        pipeline_stages:
          - docker: {}
          - labels:
              job: kubernetes
