version: '3.9'

services:
  db:
    image: timescale/timescaledb:2.13.1-pg16
    container_name: pg-db
    command: postgres -c shared_preload_libraries=timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hamster
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
